# Site settings
title: Glauxian Brothers
description: > # this means to ignore newlines until "baseurl:"
  The Glauxian Brotherhood, a band of warrior capitalists who dare to be
  bold as they fight for eternal glory, honour and economic domination.
baseurl: ""
url: "http://www.glauxian.com"

# Build settings
markdown: kramdown
